API для Content
bazalt-technologies/retelling pull request #11
Opened 2022-09-24 18:23 UTC by Argentusz

2022-09-24 18:24 UTC, Argentusz reviewed
Ещё не готово

2022-09-28 13:59 UTC, mishhgun01 reviewed
Вроде ок, теперб надо остальные методы добавить

2022-09-29 18:20 UTC, Argentusz reviewed
ОК

2022-09-29 18:27 UTC, mishhgun01 approved these changes
ОК

2022-09-29 18:27 UTC, mishhgun01 commented on pkg/storage/pgsql/content.go
> +		data.ContentID).Scan()
тут скан вроде не нужен

2022-09-29 18:27 UTC, mishhgun01 commented on pkg/storage/pgsql/content.go
> +		return models.Content{}, err
мне кажется логичнее nil,err но окей

2022-09-29 19:00 UTC, Argentusz commented on pkg/storage/pgsql/content.go
> +		return models.Content{}, err
nil не может быть типом models.Content - это же не массив

2022-09-29 19:01 UTC, Argentusz commented on pkg/storage/pgsql/content.go
> +		data.ContentID).Scan()
Если не пописать Scan у err будет тип строка базы жанных, а не error

2022-09-29 19:07 UTC, mishhgun01 commented on pkg/storage/pgsql/content.go
> +		return models.Content{}, err
согласен

2022-09-30 11:01 UTC, GarlicRoll requested changes
Необходимо учитывать зависимости
Необходимо изменить content_id в content.go на id и review_id в reviews.go на id

2022-09-30 11:01 UTC, GarlicRoll commented on pkg/storage/pgsql/content.go
> +	RETURNING content_id
У content нет content_id у него есть просто id
Это надо изменить тут и в models
(Подобное видел и в revies.go)

2022-09-30 11:18 UTC, GarlicRoll approved these changes
Все замечания учтены
Hot approve
Необходимо тестирование

2022-09-30 11:18 UTC, merged