парсинг контента и локальное хранение пользователя и его данных
bazalt-technologies/retelling pull request #26
Opened 2022-10-24 16:40 UTC by mishhgun01

2022-10-24 16:41 UTC, mishhgun01 reviewed
ОК

2022-10-25 17:25 UTC, Argentusz requested changes
В целом отлично, поправь за 10 сек моментики пж

2022-10-25 17:25 UTC, Argentusz commented on webapp/src/components/HeaderComponent.vue
> +          :selected="(modeSelected===1 || $route.path==='/content')"
думаю от modeSelected можно совсем откзаться, разве нет?

2022-10-25 17:25 UTC, Argentusz commented on webapp/src/components/MainView.vue
>        likes1: 93,
Почему кол-во лайков не привязано к длине массива лайкнувших пользователей?

2022-10-25 17:25 UTC, Argentusz commented on webapp/src/components/ButtonComponent.vue
> +  height: 32px;
Кнопик стали слишком большими и текст как-то выпадает вправо: поменяй stdBtn padding: 10px на
```
padding: 5px 10px 5px 5px;
```

2022-10-25 17:26 UTC, Argentusz commented on webapp/src/components/MainView.vue
>        likes1: 93,
Лайкнул ли юзер тоже по этому же массиву решается

2022-10-25 17:29 UTC, mishhgun01 commented on webapp/src/components/HeaderComponent.vue
> +          :selected="(modeSelected===1 || $route.path==='/content')"
+

2022-10-25 20:14 UTC, merged