SQL MODELS REVIEWS API
bazalt-technologies/retelling pull request #5
Opened 2022-07-11 08:54 UTC by GarlicRoll

Изменена схема SQL -> изменены структуры models -> изменены методы reviews
Добавлены методы для api

2022-07-11 09:07 UTC, mishhgun01 requested changes
в целом все хорошо, не без ошибок, но норм.

Немного затронул задачу максима, конечно)

2022-07-11 09:07 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +	RETURNING Id
id

2022-07-11 09:07 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +	// Чтобы можно было определить, что их трогать не надо
с этим все ок, мы же будем отправлять целое ревью, в котором некоторые поля были изменены. Получаеся, что старые данные просто перезапишутся на те же самые, а измененные на новые.

2022-07-11 09:07 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +	`,
ты же удаляешь отдельное ревью, а не все ревью у данного пользователя. поэтому where id = $1.

2022-07-15 14:20 UTC, mishhgun01 requested changes

2022-07-15 14:20 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		genre3_id,
Либо на фронте будет запрашивать и формировать эти айдишники либо на сервере. Надо подумать.

2022-07-15 14:20 UTC, mishhgun01 commented on pkg/storage/pgsql/users.go
> +	// Если да, то как передать структуру Request в GetReviews?
нет, просто выше пропиши скрипт delete from reviews where user_id=$1 и он удалит все ревью этого юзера.

2022-07-15 14:20 UTC, mishhgun01 commented on pkg/api/reviews.go
> +		_, err = api.db.DeleteReview(data.UserID)
да и лучше возвращай id, вдруг в логике понадобится, отправляй в соединение через write.

2022-07-15 14:24 UTC, GarlicRoll commented on pkg/storage/pgsql/users.go
> +	// Если да, то как передать структуру Request в GetReviews?
Слушай, правда что
Тогда и с методами для types/genres проблем нет, спасибо

2022-07-29 05:42 UTC, GarlicRoll commented
Изменение в структуре Request -> теперь там только логин/пароль + ObjectID/ObjectIDs
Добавлены методы для API + методы Get Delete Patch Update
Для users методы API переделаны: NewUser -> MethodPost, AuthUser вынесен за метод users
Хендлеры изменены в соответствии с выше описанными изменениями
+ Исправлены недочёты, которые были отмечены в ревью

2022-07-29 13:08 UTC, mishhgun01 approved these changes
Вроде ошибок нет, но лучше перед меоджем почистить код от ненужных методов

2022-07-29 13:08 UTC, mishhgun01 commented on pkg/storage/pgsql/genres.go
> +func (s *Storage) UpdateGenre(data models.Genre) (int, error) {
нужны ли нам методы обновления и добавления жанров? мы же их не меняем, они у нас остаются вбитыми в бд

2022-07-29 13:18 UTC, GarlicRoll commented on pkg/storage/pgsql/genres.go
> +func (s *Storage) UpdateGenre(data models.Genre) (int, error) {
Мы не будем их создавать как-то иначе? Я думал demodata на то и demo, что inserts только для тестирования.
Метод обновления точно нужен. Если мы захотим подправить название типа, когда у нас будет много users, то просто insert сделать не выйдет

2022-07-29 13:19 UTC, GarlicRoll commented on pkg/api/genres.go
> +	case http.MethodPatch:
Я понял, что имеется в виду то, что эти методы будут редко использоваться, но нужно ли из-за этого их удалять...

2022-07-29 13:21 UTC, mishhgun01 commented on pkg/storage/pgsql/genres.go
> +func (s *Storage) UpdateGenre(data models.Genre) (int, error) {
да нет, мы просто через sql код внесем изменения в саму бд, зачем метод для этого

2022-07-29 13:22 UTC, mishhgun01 commented on pkg/api/genres.go
> +	case http.MethodPatch:
речь о том, что они вообще не будут использоваться, файл с demodata мы просто пропишем как sql скрипт непосредственно в бд

2022-07-29 13:34 UTC, GarlicRoll commented on pkg/storage/pgsql/genres.go
> +func (s *Storage) UpdateGenre(data models.Genre) (int, error) {
Я представляю, но думаю, что удалить всегда сможем

2022-07-29 13:52 UTC, GarlicRoll commented
ОК

2022-07-29 13:56 UTC, merged