Рекомендательная система
bazalt-technologies/retelling pull request #51
Opened 2022-11-18 10:34 UTC by icekomar

2022-11-18 12:17 UTC, Argentusz requested changes

2022-11-18 12:19 UTC, Argentusz reviewed
Снято. Ждём уборку лайкнутого контента пользователем

2022-11-18 12:20 UTC, Argentusz approved these changes

2022-11-25 10:04 UTC, Argentusz requested changes
Придирки есть, хотя я в этом ничего не понимаю.
Я бы ещё разбил это на несколько функций. Функция на 150 строк - это слишком, хотя тут не настаиваю

2022-11-25 10:04 UTC, Argentusz commented on recommendation/recommendations.py
> +        genres=[0, 0, 0, 0, 0, 0, 0] #Считаем сколько количество жанров лайкнутых пользователем, для построения соотношений
(это не обязательно, но желательно, за те то деньги, что мы платим)

2022-11-25 10:08 UTC, icekomar commented on recommendation/recommendations.py
> +                n=50
цикл идет по длине, т.к. нам нужно просмотреть всех пользователей , n=50 ограничение на количество схожих пользователей

2022-11-25 10:09 UTC, icekomar commented on recommendation/recommendations.py
> +        genres=[0, 0, 0, 0, 0, 0, 0] #Считаем сколько количество жанров лайкнутых пользователем, для построения соотношений
принял

2022-11-25 10:20 UTC, icekomar commented on recommendation/recommendations.py
> +        genres=[0, 0, 0, 0, 0, 0, 0] #Считаем сколько количество жанров лайкнутых пользователем, для построения соотношений
сделал

2022-11-25 11:30 UTC, Argentusz approved these changes

2022-11-27 15:44 UTC, GarlicRoll reviewed
не используются объекты из models к сожалению, он возвращает список Ids или json ?

2022-11-28 11:35 UTC, icekomar commented
Список  ids

2022-12-14 10:45 UTC, merged