Starting remaking database to content
bazalt-technologies/retelling pull request #6
Opened 2022-09-10 20:23 UTC by Argentusz

2022-09-11 12:26 UTC, mishhgun01 requested changes
логика хорошая, но ты ее не доделал до конца.
мне видится так: нужен еще метод storage для получения контента по айди, создание нового контента и метод для получения айдишек ревью для данного айди контента (для будущей рекомендательной системы).
Ну и неплохо было бы сразу хэндлеры сюда вкрутить

2022-09-11 12:26 UTC, mishhgun01 commented on pkg/SQL/schema.sql
> +    ContentID INTEGER NOT NULL,
лучше придерживаться единой стилистики при именовании переменных. в sql принято называть в snake-case и нижнем регистре и у нас большинство переменных в sql именно так названы, так что лучше не выделять и сделать по шаблону review_id итд

2022-09-11 12:26 UTC, mishhgun01 commented on pkg/SQL/schema.sql
> +    ContentID SERIAL PRIMARY KEY,
ну и тут собственно то же самое

2022-09-11 12:26 UTC, mishhgun01 commented on pkg/SQL/schema.sql
> +    ContentID INTEGER NOT NULL,
тут у id контента не хвататет references

2022-09-11 12:26 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		genre3,
согласно обновленной схеме, у reviews нет полей жанров. они есть у контента

2022-09-11 12:28 UTC, mishhgun01 commented
блин и моя личная просьба делай описания на русском пж. не хочется сильно вдумываться и переводить чтобы понимать изменения

2022-09-11 13:56 UTC, GarlicRoll reviewed
По snake case согласен с МГ, по логике - главное просто создать новую структуру и поменять немного поля - на основе этого откорректировать методы

2022-09-11 13:56 UTC, GarlicRoll commented on pkg/SQL/schema.sql
> +CREATE TABLE review (
Я бы просто убрал поля, относящиеся к content, вроде genre
Даже types необходимо оставить, чтобы понимать "направление" именного этого ревью (по угару/серьезный/поплакать)

2022-09-11 13:56 UTC, GarlicRoll commented on pkg/models/models.go
> -	Genre  string
Зачем тут жанры, если они теперь для content

2022-09-11 13:56 UTC, GarlicRoll commented on pkg/storage/pgsql/reviews.go
> +func (s *Storage) PatchReview(data models.Review) error {
Я может не вижу, но такой patchReview точно уже был

2022-09-21 11:31 UTC, Argentusz reviewed
OK

2022-09-21 13:50 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		review_id,
айди само высчитывается, его вносить не надо

2022-09-21 13:52 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		content_id,
то же самое про id и returning

2022-09-21 13:53 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		user_id,
не нужен нам user_id если мы по нему получаем ревью

2022-09-21 13:56 UTC, Argentusz commented on pkg/storage/pgsql/reviews.go
> +		user_id,
А я считаю, что в общем случае надо бы. Мало ли куда это передается, удобнее, если в респонде оно будет и не нужно будет в итоге передавать эту хуйню отдельной переменной?

2022-09-21 14:27 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		user_id,
ты ж в методе апи будешь вызывать этот метод бд =>  будешь отправлять айдишник из хэндлера в этот метод, так и нахера его возвращать обратно?

2022-09-21 14:29 UTC, Argentusz commented on pkg/storage/pgsql/reviews.go
> +		user_id,
Ну ты где-то вызываешь этот хэндлер, чтобы данные передать в другую функцию в микросервисе к примеру

2022-09-21 14:37 UTC, Argentusz reviewed
OK

2022-09-21 17:37 UTC, mishhgun01 reviewed
ну блин исправь....

2022-09-21 17:37 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		data.ReviewID,
откуда ReviewID?

2022-09-21 17:37 UTC, mishhgun01 commented on pkg/storage/pgsql/reviews.go
> +		data.ContentID,
тут тоже не должно быть ContentID

2022-09-23 09:20 UTC, mishhgun01 approved these changes
вроде ок

2022-09-23 17:05 UTC, GarlicRoll approved these changes
Я посмотрел, вроде изменили всё, что нужно
сейчас главное запустить наконец этот серевр
аппрув

2022-09-24 08:51 UTC, merged